version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y git autoconf automake libxml++2.6-dev libicu-dev libtool gettext python3
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - git clone https://github.com/voikko/corevoikko.git
      - git clone https://github.com/hfst/hfst-ospell.git
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - export PWD=`pwd` && export PREFIX=${PWD}/opt && find . > files.txt && cd ${PWD}/hfst-ospell && ./autogen.sh && ./configure --without-libxmlpp --prefix="${PREFIX}" && make && make install && export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" && cd ${PWD}/corevoikko/libvoikko && ./autogen.sh && ./configure --prefix="${PREFIX}" && make && make install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - apache.ini
    - bin
    - bin/voikkovfstc
    - bin/voikkogc
    - bin/voikkohyphenate
    - bin/hfst-ospell-office
    - bin/hfst-ospell
    - bin/voikkospell
    - build
    - build/bdist.linux-x86_64
    - corevoikko
    - development.ini
    - dist
    - dist/aleksi-0.0.0-py3.4.egg
    - enwiktlookup
    - enwiktlookup/make.sh
    - enwiktlookup/src
    - enwiktlookup/src/main
    - enwiktlookup/src/main/java
    - enwiktlookup/src/main/java/com
    - enwiktlookup/src/main/java/com/mycompany
    - enwiktlookup/src/main/java/com/mycompany/app
    - enwiktlookup/src/main/java/com/mycompany/app/MainClass.java
    - enwiktlookup/target
    - enwiktlookup/target/classes
    - enwiktlookup/target/classes/com
    - enwiktlookup/target/classes/com/mycompany
    - enwiktlookup/target/classes/com/mycompany/app
    - enwiktlookup/target/classes/com/mycompany/app/MainClass.class
    - enwiktlookup/target/archive-tmp
    - enwiktlookup/pom.xml
    - enwiktlookup/jwktl-1.0.1.jar
    - enwiktlookup.jar
    - files.txt
    - get_verbs.py
    - hfst-ospell
    - include
    - include/hfstol-stdafx.h
    - include/libvoikko
    - include/libvoikko/voikko_structs.h
    - include/libvoikko/voikko_enums.h
    - include/libvoikko/voikko_defines.h
    - include/libvoikko/voikko_deprecated.h
    - include/libvoikko/voikko.h
    - include/ol-exceptions.h
    - include/ospell.h
    - include/ZHfstOspellerXmlMetadata.h
    - include/ZHfstOspeller.h
    - include/hfst-ol.h
    - initdb.py
    - INSTALL.md
    - aleksi
    - aleksi/libvoikko.py
    - aleksi/content
    - aleksi/content/js
    - aleksi/content/js/lookup0.js
    - aleksi/content/js/jquery-3.0.0.min.js
    - aleksi/content/js/word_under_cursor.js
    - aleksi/content/js/jquery-ui-1.12.0
    - aleksi/content/js/jquery-ui-1.12.0/index.html
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.structure.css
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.min.js
    - aleksi/content/js/jquery-ui-1.12.0/LICENSE.txt
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.min.css
    - aleksi/content/js/jquery-ui-1.12.0/images
    - aleksi/content/js/jquery-ui-1.12.0/images/ui-icons_444444_256x240.png
    - aleksi/content/js/jquery-ui-1.12.0/images/ui-icons_ffffff_256x240.png
    - aleksi/content/js/jquery-ui-1.12.0/images/ui-icons_777777_256x240.png
    - aleksi/content/js/jquery-ui-1.12.0/images/ui-icons_555555_256x240.png
    - aleksi/content/js/jquery-ui-1.12.0/images/ui-icons_cc0000_256x240.png
    - aleksi/content/js/jquery-ui-1.12.0/images/ui-icons_777620_256x240.png
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.structure.min.css
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.theme.min.css
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.js
    - aleksi/content/js/jquery-ui-1.12.0/package.json
    - aleksi/content/js/jquery-ui-1.12.0/external
    - aleksi/content/js/jquery-ui-1.12.0/external/jquery
    - aleksi/content/js/jquery-ui-1.12.0/external/jquery/jquery.js
    - aleksi/content/js/jquery-ui-1.12.0/AUTHORS.txt
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.css
    - aleksi/content/js/jquery-ui-1.12.0/jquery-ui.theme.css
    - aleksi/content/js/lookup.js
    - aleksi/content/css
    - aleksi/content/css/lookup.css
    - aleksi/content/css/reader.css
    - aleksi/content/websites
    - aleksi/content/aleksi_dialog.pt
    - aleksi/__init__.py
    - aleksi/__init__.pyc
    - aleksi/templates
    - aleksi/templates/link_website_form.pt
    - aleksi/templates/aleksi_data.pt
    - aleksi/templates/website_index.pt
    - aleksi/templates/aleksi_data_dl.pt
    - aleksi/models
    - aleksi/models/__init__.py
    - aleksi/models/feed.py
    - aleksi/models/sanakirja.py
    - aleksi/models/website.py
    - aleksi.egg-info
    - aleksi.egg-info/entry_points.txt
    - aleksi.egg-info/dependency_links.txt
    - aleksi.egg-info/top_level.txt
    - aleksi.egg-info/PKG-INFO
    - aleksi.egg-info/requires.txt
    - aleksi.egg-info/SOURCES.txt
    - aleksi.sqlite
    - lib
    - lib/pkgconfig
    - lib/pkgconfig/hfstospell.pc
    - lib/pkgconfig/libvoikko.pc
    - lib/libvoikko.so.1
    - lib/libvoikko.a
    - lib/libhfstospell.so.9.0.0
    - lib/libvoikko.la
    - lib/libvoikko.so.1.14.5
    - lib/libhfstospell.a
    - lib/libhfstospell.so
    - lib/libvoikko.so
    - lib/libhfstospell.so.9
    - lib/libhfstospell.la
    - lookup.pl
    - passwd
    - README.md
    - requirements.txt
    - setup.py
    - share
    - share/man
    - share/man/man1
    - share/man/man1/voikkogc.1
    - share/man/man1/hfst-ospell-office.1
    - share/man/man1/voikkospell.1
    - share/man/man1/hfst-ospell.1
    - share/man/man1/voikkovfstc.1
    - share/man/man1/voikkohyphenate.1
    - TODO.md
    - wsgi.py
  discard-paths: no 
